# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "underflow"
license = "MIT"
licenselink = "https://github.com/oxalorg/hugo-sunderflow/blob/master/LICENSE.md"
description = ""
homepage = "https://securityunderflow.com"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "oxalorg"
  homepage = "https://oxal.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
